### ISSUE TITLE
Examples says that you can expect 5 to be a Number but it fails

### ISSUE THREAD

**Issue by pmarques** [Automattic/expect.js#128]
Just require
```
expect = require('expect.js');
expect(5).to.be.a(Number);
```

It throws an execption:
```
Error: expected 5 to be an instance of Number
    at Assertion.assert (expect.js/index.js:96:13)
    at Assertion.a.Assertion.an [as a] (expect.js/index.js:279:12)
    at Function.a (expect.js/index.js:499:17)
    at repl:1:17
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
```

I'm using version 0.3.1

**Comment by janmarek** [comment]
Try expect(5).to.be.a('number')

**Comment by rauchg** [comment]
Fixed

**Comment by rase-** [comment]
By fixed, meaning that the example was removed. Use `expect(5).to.be.a('number')` instead.

**Comment by janmarek** [comment]
@rauchg A commit after almost one year. Great to see that ;) Can you please fix the tests? https://github.com/janmarek/expect2/commit/0b6ab560015f8045be065a6458552c72740e1ff5
